[package]
name = "broadcast-server-example"
version = "0.1.0"
edition = "2021"

[dependencies]
futures = "0.3"
tokio = { version = "1.38", features = ["full"] }
tokio-util = { version = "0.7.14", features = ["codec"] }
